Repository railwayapp/cli, pull requests merged in 2022-02, with the labels that each got.

#182 Install binary correctly with NPM
  npm-install/config.js
  npm-install/postinstall.js
  package-lock.json
  package.json
Labels: release/minor, release/major

#188 README
  README.md
Labels: release/major

#190 Added node engine warning
  package.json
Labels: release/minor

#192 Use node 16 in github CI
  .github/workflows/publish.yml
Labels: release/patch

#193 Install binary correctly with NPM (again)
  .gitignore
  bin/railway.js
  package-lock.json
  package.json
Labels: release/patch

#195 Patch Bump
  npm-install/postinstall.js
Labels: release/patch

#196 Silent Close
  bin/railway.js
Labels: release/patch

#197 Update yarn command
  README.md
Labels: release/patch

#187 Add ignore file
  cmd/up.go
  controller/up.go
Labels: release/minor

#177 Follow symlinks and make a copy at the link
  controller/up.go
Labels: release/patch

#194 Verbose mode for `railway up`
  cmd/up.go
  main.go
  ui/text.go
Labels: release/patch

#203 fix npm install for windows
  npm-install/postinstall.js
Labels: release/patch
