Repository railwayapp/cli, pull requests merged in 2023-10, with the labels that each got.

#457 Lint
  src/commands/logs.rs
  src/commands/up.rs
Labels: release/skip

#453 Allow service to be selected in `railway link`
  src/commands/link.rs
  src/errors.rs
  src/gql/queries/strings/Projects.graphql
  src/gql/queries/strings/UserProjects.graphql
Labels: release/minor

#451 Improve clarity in `railway shell` without a service being linked
  src/commands/shell.rs
Labels: release/patch

#456 Fix up from automatically selecting a service
  src/commands/run.rs
  src/commands/up.rs
Labels: release/patch

#458 Support `railway connect` for service databases
  .cargo/config
  src/commands/connect.rs
  src/controllers/project.rs
  src/controllers/variables.rs
  src/errors.rs
  src/gql/queries/strings/Project.graphql
  src/gql/schema.graphql
Labels: release/minor

#460 Add context if terminal is TTY
  src/commands/up.rs
Labels: release/patch

#461 support linking to services with no services
  src/commands/link.rs
Labels: release/patch
