Repository railwayapp/cli, pull requests merged in 2023-09, with the labels that each got.

#449 Remove confusing wording in `railway run`
  src/commands/run.rs
  src/subscription.rs
Labels: release/patch

#437 feat: add silent flag to shell
  src/commands/shell.rs
Labels: release/minor

#430 fix: Update README Homebrew instructions
  README.md
Labels: release/skip

#429 Add deloyment id to logs
  src/commands/logs.rs
Labels: release/minor

#443 Refactor to shell & inline comments for maintainence
  src/commands/shell.rs
Labels: release/patch
