Repository railwayapp/cli, pull requests merged in 2023-04, with the labels that each got.

#406 update the package.json version on `cargo release`
  release.toml
Labels: release/patch

#407 update package.json files
  package.json
Labels: release/skip

#412 early return in shell if no environment variables present
  src/commands/shell.rs
Labels: release/patch

#411 fix<shell>: fixes shell responding to ctrl-c when it shouldn't
  src/commands/shell.rs
Labels: release/minor

#413 [command] [up] ignore .git and node_modules by default
  src/commands/up.rs
Labels: release/minor

#409 feat: windows specific shell detection
  Cargo.lock
  Cargo.toml
  src/commands/shell.rs
Labels: release/minor

#410 fix<run>: allows `railway run` to run batch scripts on windows, including pnpm and npm.
  src/commands/run.rs
Labels: release/patch

#416 fix<shell>: remove dbg! macro in windows shell detection
  src/commands/shell.rs
Labels: release/skip

#414 Better CLI errors
  Cargo.lock
  Cargo.toml
  src/client.rs
  src/commands/add.rs
  src/commands/connect.rs
  src/commands/delete.rs
  src/commands/docs.rs
  src/commands/domain.rs
  src/commands/down.rs
  src/commands/environment.rs
  src/commands/init.rs
  src/commands/link.rs
  src/commands/list.rs
  src/commands/login.rs
  src/commands/logs.rs
  src/commands/run.rs
  src/commands/service.rs
  src/commands/shell.rs
  src/commands/status.rs
  src/commands/unlink.rs
  src/commands/up.rs
  src/commands/variables.rs
  src/commands/whoami.rs
  src/config.rs
  src/consts.rs
  src/controllers/environment.rs
  src/controllers/mod.rs
  src/controllers/plugin.rs
  src/controllers/project.rs
  src/controllers/user.rs
  src/controllers/variables.rs
  src/errors.rs
  src/gql/queries/mod.rs
  src/gql/queries/strings/Project.graphql
  src/gql/queries/strings/ProjectPlugins.graphql
  src/main.rs
  src/util/prompt.rs
Labels: release/minor

#351 Add --environment flag for railway up
  src/commands/up.rs
Labels: release/minor

#417 Run `cargo update`
  Cargo.lock
Labels: release/skip

#418 Stream both build and deploy logs for up command
  src/commands/logs.rs
  src/commands/up.rs
  src/controllers/deployment.rs
  src/controllers/mod.rs
  src/gql/queries/mod.rs
  src/gql/queries/strings/Deployment.graphql
  src/gql/queries/strings/Deployments.graphql
  src/gql/schema.graphql
Labels: release/minor

#419 fix(cmd): Describe `railway connect` properly
  src/commands/connect.rs
Labels: release/patch

#420 do not unwrap in up command
  src/commands/up.rs
Labels: release/patch
