Repository railwayapp/cli, pull requests merged in 2023-03, with the labels that each got.

#306 fix release workflow
  .github/workflows/ci.yml
  .github/workflows/release.yml
  install.sh
Labels: release/patch

#308 rename install script bins
  install.sh
Labels: release/patch

#310 fixes `railway service`
  src/commands/service.rs
Labels: release/patch

#311 Log `railway shell` and fix logs for `up`
  README.md
  src/commands/shell.rs
  src/commands/up.rs
Labels: release/patch

#312 add npm release workflows
  .github/workflows/publish.yml
  .gitignore
  npm-install/config.js
  npm-install/postinstall.js
  package.json
  pnpm-lock.yaml
Labels: release/patch

#313 simplify npm workflow
  .github/workflows/publish.yml
  README.md
  package.json
Labels: release/patch

#323 Clean-up code
  .cargo/config
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  src/commands/add.rs
  src/commands/delete.rs
  src/commands/docs.rs
  src/commands/init.rs
  src/commands/login.rs
  src/commands/service.rs
  src/commands/unlink.rs
  src/commands/up.rs
  src/commands/variables.rs
  src/subscription.rs
  src/util/prompt.rs
Labels: release/skip

#322 Add install instructions for Scoop
  README.md
Labels: release/skip

#325 release tarfiles for windows
  .github/workflows/release.yml
  bin/railway.js
  npm-install/config.js
  npm-install/postinstall.js
Labels: release/patch

#326 Allow setting the project name as a parameter of init command
  src/commands/init.rs
Labels: release/patch

#327 fix railway run when there are no services
  src/commands/run.rs
Labels: release/patch

#328 Use constants in more places
  src/commands/run.rs
  src/commands/shell.rs
  src/commands/variables.rs
Labels: release/skip

#330 fixes the unlink command
  src/commands/unlink.rs
Labels: release/patch

#332 release binary for `x86_64-pc-windows-gnu`
  .github/workflows/release.yml
Labels: release/patch

#333 don't use `$module:tt` in macros
  src/macros.rs
Labels: release/skip

#334 allow user to select service on `up`
  src/commands/add.rs
  src/commands/delete.rs
  src/commands/docs.rs
  src/commands/domain.rs
  src/commands/login.rs
  src/commands/open.rs
  src/commands/service.rs
  src/commands/up.rs
  src/commands/variables.rs
  src/macros.rs
  src/util/prompt.rs
Labels: release/patch

#335 make script compatible with `dash`
  install.sh
Labels: release/skip

#342 Render service variables for `railway variables`, `railway shell`, and `railway run`
  src/commands/run.rs
  src/commands/service.rs
  src/commands/shell.rs
  src/commands/variables.rs
  src/controllers/mod.rs
  src/controllers/variables.rs
  src/gql/queries/mod.rs
  src/gql/queries/strings/VariablesForPlugin.graphql
  src/gql/queries/strings/VariablesForServiceDeployment.graphql
  src/gql/schema.graphql
  src/main.rs
Labels: release/patch

#345 fix config race condition
  src/commands/run.rs
  src/config.rs
Labels: release/patch

#341 fix npm install on windows
  npm-install/config.js
  npm-install/postinstall.js
Labels: release/patch

#346 fix `run` command environment arg resolution
  src/commands/run.rs
Labels: release/patch

#381 fix generation of `.tar.gz` archives on windows
  .github/workflows/release.yml
Labels: release/skip

#380 release binary for `i686-pc-windows-gnu`
  .github/workflows/release.yml
Labels: release/skip

#387 Fix `railway up` in CI environments
  src/config.rs
Labels: release/patch

#388 Ignore CTRL+C on `railway run`
  Cargo.lock
  Cargo.toml
  src/commands/run.rs
Labels: release/patch

#397 Connect command
  Cargo.lock
  Cargo.toml
  src/commands/connect.rs
  src/commands/mod.rs
  src/consts.rs
  src/controllers/variables.rs
  src/gql/queries/strings/Project.graphql
  src/gql/queries/strings/ProjectPlugins.graphql
  src/main.rs
  src/util/prompt.rs
Labels: release/minor

#392 Update `open` off of yanked version
  Cargo.lock
  Cargo.toml
Labels: release/patch

#400 exit with the same exit code as process for railway run
  src/commands/run.rs
Labels: release/patch

#389 fix build on `i686-pc-windows-gnu`
  .github/workflows/release.yml
Labels: release/patch

#403 Write config tmp file in same directory
  src/config.rs
Labels: release/patch
