Repository railwayapp/cli, pull requests merged in 2024-09, with the labels that each got.

#542 Handle null values in service variables
  src/commands/shell.rs
  src/commands/variables.rs
  src/controllers/variables.rs
  src/gql/queries/mod.rs
Labels: release/minor

#545 handle `railway login` when api token is set
  src/commands/login.rs
  src/commands/whoami.rs
  src/config.rs
  src/errors.rs
Labels: release/minor

#548 Clippy fixes
  src/commands/connect.rs
Labels: release/skip

#546 show next steps when linking a project
  src/commands/link.rs
Labels: release/minor

#549 Add `railway env` as an alias for `railway environment`
  src/macros.rs
  src/main.rs
Labels: release/skip

#547 Allow setting variables via `--set`
  src/commands/add.rs
  src/commands/deploy.rs
  src/commands/down.rs
  src/commands/variables.rs
  src/controllers/variables.rs
  src/gql/mutations/mod.rs
  src/gql/mutations/strings/VariableCollectionUpsert.graphql
  src/gql/queries/mod.rs
  src/gql/schema.graphql
Labels: release/minor

#551 `railway link` improvements
  .gitignore
  Cargo.lock
  Cargo.toml
  src/commands/link.rs
  src/errors.rs
  src/gql/queries/strings/UserProjects.graphql
Labels: release/patch

#552 Clippy fixes (once more)
  src/gql/mutations/mod.rs
  src/gql/queries/mod.rs
Labels: release/skip
