Repository railwayapp/cli, pull requests merged in 2024-08, with the labels that each got.

#527 Minor fixes
  shell.nix
  src/commands/link.rs
Labels: release/skip

#528 Link project on deploy
  src/commands/deploy.rs
Labels: release/patch

#526 Remove brew tap from instructions
  README.md
Labels: release/skip

#525 Clippy fixes
  src/commands/add.rs
  src/commands/deploy.rs
  src/commands/domain.rs
Labels: release/skip

#530 Fix Docker publish workflow
  .github/workflows/docker-publish.yml
  .github/workflows/publish-docker.yml
  .github/workflows/release.yml
  Dockerfile
Labels: release/minor

#532 Connect to public database URLs
  src/commands/connect.rs
  src/errors.rs
Labels: release/patch

#531 Fix exec permission in docker image
  Dockerfile
Labels: release/patch

#533 Added AUR instructions to readme
  README.md
Labels: release/skip

#534 notify discord on release
  .github/workflows/release.yml
Labels: release/patch

#535 Include docker instructions in readme
  README.md
Labels: release/skip

#537 Fix up command CI mode and status subscription
  README.md
  src/commands/deploy.rs
  src/commands/up.rs
  src/config.rs
  src/gql/schema.graphql
  src/gql/subscriptions/mod.rs
  src/gql/subscriptions/strings/Deployment.graphql
  src/gql/subscriptions/strings/DeploymentEvents.graphql
Labels: release/minor

#540 fix: format `CONTRIBUTING.md`
  CONTRIBUTING.md
Labels: release/skip

#541 better error messages when project or environment is deleted
  src/commands/add.rs
  src/commands/deploy.rs
  src/commands/domain.rs
  src/commands/environment.rs
  src/commands/logs.rs
  src/commands/open.rs
  src/commands/redeploy.rs
  src/commands/run.rs
  src/commands/service.rs
  src/commands/shell.rs
  src/commands/status.rs
  src/commands/up.rs
  src/commands/variables.rs
  src/commands/volume.rs
  src/controllers/project.rs
  src/errors.rs
  src/gql/queries/strings/Project.graphql
Labels: release/patch
