Repository railwayapp/cli, pull requests merged in 2024-06, with the labels that each got.

#500 Add volume support to the CLI
  src/commands/mod.rs
  src/commands/volume.rs
  src/errors.rs
  src/gql/mutations/mod.rs
  src/gql/mutations/strings/VolumeAttach.graphql
  src/gql/mutations/strings/VolumeCreate.graphql
  src/gql/mutations/strings/VolumeDelete.graphql
  src/gql/mutations/strings/VolumeDetach.graphql
  src/gql/mutations/strings/VolumeMountPathUpdate.graphql
  src/gql/mutations/strings/VolumeNameUpdate.graphql
  src/gql/queries/strings/Project.graphql
  src/main.rs
  src/util/prompt.rs
Labels: release/minor

#501 bump MSRV to 1.70.0
  Cargo.toml
Labels: release/skip

#502 Optimise binary size
  Cargo.toml
Labels: release/skip

#505 verbose railway up flag
  src/commands/up.rs
Labels: release/patch

#504 Fix timeout & and add spinner
  src/client.rs
  src/commands/volume.rs
Labels: release/patch

#506 `railway up --ci` now waits for healthchecks
  src/commands/up.rs
  src/controllers/deployment.rs
  src/gql/queries/mod.rs
  src/gql/queries/strings/Deployment.graphql
  src/gql/schema.graphql
  src/gql/subscriptions/mod.rs
  src/gql/subscriptions/strings/DeploymentEvents.graphql
Labels: release/minor

#508 Fix service command showing services that aren't in current environment
  src/commands/service.rs
Labels: release/patch

#509 Fix release CI and NPM CI
  .github/workflows/ci.yml
  .github/workflows/publish-npm.yml
  .github/workflows/release.yml
Labels: release/skip

#510 `railway redeploy`
  src/commands/mod.rs
  src/commands/redeploy.rs
  src/gql/mutations/mod.rs
  src/gql/mutations/strings/DeploymentRedeploy.graphql
  src/gql/queries/strings/Project.graphql
  src/main.rs
Labels: release/minor

#511 Fix bad formatting
  src/commands/up.rs
Labels: release/patch

#514 Fix CLI compilation
  .gitignore
  Cargo.lock
  Cargo.toml
  flake.nix
  shell.nix
  src/commands/login.rs
  src/errors.rs
Labels: release/patch

#515 chore: Release railwayapp version 3.9.2
  Cargo.lock
  Cargo.toml
  package.json
Labels: release/patch

#516 Deploy template from CLI
  .gitignore
  src/commands/deploy.rs
  src/commands/mod.rs
  src/gql/queries/mod.rs
  src/gql/queries/strings/TemplateDetail.graphql
  src/main.rs
Labels: release/minor

#518 Make add command use deploy internals
  src/commands/add.rs
  src/commands/deploy.rs
Labels: release/minor
