Repository railwayapp/cli, pull requests merged in 2024-10, with the labels that each got.

#554 Fix login issue
  src/commands/login.rs
Labels: release/patch

#555 Add feedback after link
  src/commands/link.rs
Labels: release/patch

#559 Update README.md
  README.md
Labels: release/skip

#564 Upgrade dependencies
  Cargo.lock
  Cargo.toml
  src/config.rs
Labels: release/skip

#563 Template deploy v2
  CONTRIBUTING.md
  build.rs
  src/commands/add.rs
  src/commands/deploy.rs
  src/controllers/database.rs
  src/gql/mutations/mod.rs
  src/gql/mutations/strings/TemplateDeploy.graphql
  src/gql/queries/mod.rs
  src/gql/queries/strings/TemplateDetail.graphql
  src/gql/schema.graphql
  src/gql/schema.json
  src/gql/subscriptions/mod.rs
Labels: release/minor

#566 create draft release before publishing
  .github/workflows/release.yml
Labels: release/patch

#567 fix asset releases
  .github/workflows/release.yml
Labels: release/patch

#568 publish to npm as part of release workflow
  .github/workflows/publish-npm.yml
  .github/workflows/release.yml
Labels: release/skip

#569 only shortcircuit the login command if the RAILWAY_API_TOKEN is found
  src/commands/login.rs
Labels: release/patch
