Repository railwayapp/cli, pull requests merged in 2024-04, with the labels that each got.

#487 Remove references to plugins
  Cargo.lock
  Cargo.toml
  src/commands/add.rs
  src/commands/connect.rs
  src/commands/delete.rs
  src/commands/mod.rs
  src/commands/run.rs
  src/commands/status.rs
  src/commands/variables.rs
  src/consts.rs
  src/controllers/database.rs
  src/controllers/mod.rs
  src/controllers/plugin.rs
  src/controllers/project.rs
  src/controllers/variables.rs
  src/errors.rs
  src/gql/mutations/mod.rs
  src/gql/mutations/strings/PluginCreate.graphql
  src/gql/mutations/strings/PluginDelete.graphql
  src/gql/mutations/strings/TemplateDeploy.graphql
  src/gql/queries/mod.rs
  src/gql/queries/strings/Project.graphql
  src/gql/queries/strings/TemplateDetail.graphql
  src/gql/queries/strings/VariablesForPlugin.graphql
  src/gql/schema.graphql
  src/main.rs
  src/util/prompt.rs
Labels: release/minor, community

#488 fix: update version to match with latest release
  Cargo.lock
  Cargo.toml
  package.json
Labels: release/skip, community

#477 Support CICD
  src/commands/up.rs
Labels: release/minor

#490 use --ci flag instead of --cicd
  src/commands/up.rs
Labels: release/minor

#492 Rewrite link command
  Cargo.lock
  Cargo.toml
  src/commands/link.rs
  src/gql/queries/strings/Project.graphql
  src/gql/queries/strings/Projects.graphql
  src/gql/queries/strings/UserProjects.graphql
  src/util/prompt.rs
Labels: release/patch, community
