Repository railwayapp/cli, pull requests merged in 2025-09, with the labels that each got.

#661 Add CLAUDE.md with development guidance
  CLAUDE.md
  src/commands/add.rs
  src/util/check_update.rs
Labels: release/skip

#663 Fix environment duplication timeout when process takes longer than 30s
  src/commands/environment.rs
  src/gql/mutations/strings/EnvironmentCreate.graphql
  src/gql/queries/mod.rs
  src/gql/queries/strings/EnvironmentStagedChanges.graphql
  src/gql/schema.json
Labels: release/minor

#665 longer log retry
  src/controllers/deployment.rs
Labels: release/patch

#667 Add `--lines` / `-n` and `-f` / `--filter` options to log command
  .github/workflows/ci.yml
  src/commands/logs.rs
  src/commands/up.rs
  src/controllers/deployment.rs
  src/gql/queries/strings/BuildLogs.graphql
  src/gql/queries/strings/DeploymentLogs.graphql
  src/gql/subscriptions/strings/BuildLogs.graphql
  src/util/logs.rs
Labels: release/minor

#671 Fix for `railway logs`: allow using deployment ID to look up failed build logs
  src/commands/logs.rs
Labels: release/patch

#673 Add `deployment` command with subcommands for list, up and redeploy
  src/commands/deployment.rs
  src/commands/down.rs
  src/commands/logs.rs
  src/commands/mod.rs
  src/gql/queries/strings/Deployments.graphql
  src/main.rs
Labels: release/minor

#674 Replace no longer maintained `paste` crate
  Cargo.lock
  Cargo.toml
  src/macros.rs
Labels: release/skip
