Repository railwayapp/cli, pull requests merged in 2025-03, with the labels that each got.

#598 add `ssh` command
  Cargo.lock
  Cargo.toml
  src/commands/mod.rs
  src/commands/ssh.rs
  src/commands/up.rs
  src/config.rs
  src/controllers/mod.rs
  src/controllers/service.rs
  src/controllers/terminal.rs
  src/main.rs
Labels: release/minor

#600 send a ping to ensure websocket connection does not close
  src/controllers/terminal.rs
Labels: release/patch

#577 feat: add check updates command
  Cargo.toml
  src/commands/check_updates.rs
  src/commands/init.rs
  src/commands/link.rs
  src/commands/mod.rs
  src/commands/run.rs
  src/config.rs
  src/main.rs
  src/util/check_update.rs
  src/util/compare_semver.rs
  src/util/mod.rs
Labels: release/minor

#605 impl command mode for ssh
  src/commands/ssh.rs
  src/commands/ssh/common.rs
  src/commands/ssh/mod.rs
  src/commands/ssh/platform/mod.rs
  src/commands/ssh/platform/unix.rs
  src/commands/ssh/platform/windows.rs
  src/controllers/terminal/client.rs
  src/controllers/terminal/connection.rs
  src/controllers/terminal/messages.rs
  src/controllers/terminal/mod.rs
Labels: release/minor

#610 Properly show external workspaces
  Cargo.lock
  Cargo.toml
  src/commands/init.rs
  src/commands/link.rs
  src/commands/list.rs
  src/commands/ssh/common.rs
  src/commands/ssh/mod.rs
  src/commands/ssh/platform/unix.rs
  src/commands/up.rs
  src/config.rs
  src/controllers/terminal/client.rs
  src/controllers/terminal/connection.rs
  src/controllers/terminal/mod.rs
  src/errors.rs
  src/gql/queries/strings/UserProjects.graphql
  src/gql/schema.json
  src/main.rs
  src/workspace.rs
Labels: release/major

#596 Adds a flag for correct uploading of project subdirs
  src/commands/up.rs
Labels: release/minor

#609 fix: make –no-gitignore actually work
  src/commands/up.rs
Labels: release/patch

#612 fix bail import
  src/commands/up.rs
Labels: release/skip
