Repository railwayapp/cli, pull requests merged in 2025-02, with the labels that each got.

#588 Fix open command
  src/commands/open.rs
Labels: release/patch

#587 Add `railway environment new` and `railway environment delete`
  Cargo.toml
  src/commands/environment.rs
  src/commands/mod.rs
  src/errors.rs
  src/gql/mutations/mod.rs
  src/gql/mutations/strings/EnvironmentCreate.graphql
  src/gql/mutations/strings/EnvironmentDelete.graphql
  src/gql/queries/mod.rs
  src/util/prompt.rs
Labels: release/minor

#589 Fix sealed variables
  src/controllers/variables.rs
  src/gql/queries/mod.rs
Labels: release/patch

#591 Fix link command for non-terminal usage
  src/commands/link.rs
Labels: release/patch

#592 Fix docker ci workflow
  .github/workflows/publish-docker.yml
Labels: release/skip

#593 Fix manual docker ci tag
  .github/workflows/publish-docker.yml
Labels: release/skip

#594 format manual docker deployment tag
  .github/workflows/publish-docker.yml
Labels: release/skip
